# Workflow to test build the docusaurus documentation page
# This workflow can be included for pull request rules to succeed

name: Build test

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main

env:
  IMAGE: europe-west4-docker.pkg.dev/sacred-sol-99413/setu/documentation

jobs:
  setup-build:
    name: Setup and build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker build
      run: |-
        docker build \
          --tag "$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .